version: "3"

services:
  app:
    build: app
    restart: always
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ../:/usr/src/app
    working_dir: /usr/src/app
    environment:
      ADDRESS: app:8000
  database:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
