version: "3"

services:
  app:
    build:
      context: ../
      dockerfile: docker/app/dockerfile
    restart: always
    tty: true
    volumes:
      - ../src:/usr/src/app
    working_dir: /usr/src/app
  # database:
  #   image: mysql:8.0
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./db/initdb:/docker-entrypoint-initdb.d
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
